In [105]:
import os, sys
import torch.nn.functional as F
import torch
import torch.nn as nn
import collections
import quanti as qt
import numpy as np

ModuleNotFoundError: No module named 'nn'

In [103]:
class GoldenSpatialModel(nn.Module):
    def __init__(self):
        super(GoldenSpatialModel, self).__init__()
        self.Linear0 = nn.Linear(256,10)
        self.Linear1 = nn.Linear(10,2)
        
    def forward(self, input_data):
        x_scale = qt.data_scale_gen(input_data,'Linear0','Linear_input')
        x = qt.quantize_data(input_data, x_scale)
        print(x.dtype)
        y = self.Linear0(x)
        z = self.Linear1(y)
        
        return z
        

In [104]:
def main():
    with torch.no_grad():
        model = GoldenSpatialModel()
    #     for name,param in model.named_parameters():
    #         print("name:")
    #         print(name)
    #         print("param:")
    #         print(param)
        print("another test:")
    #     print(model.named_parameters()['Linear.weight'])
        param_list = collections.OrderedDict()
        param_list['Linear0.weight'] = torch.ones(10,256)
        param_list['Linear0.bias'] = torch.zeros(10)
        param_list['Linear1.weight'] = torch.ones(2,10)
        param_list['Linear1.bias'] = torch.zeros(2)
    #     print(param_list)
        model.load_state_dict(param_list)
        print(list(model.named_parameters()))
        input_data = torch.randn(1,256)
        res = model(input_data)
        print(res)
    
if __name__ == '__main__':
    main()
    

another test:
[('Linear0.weight', Parameter containing:
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], requires_grad=True)), ('Linear0.bias', Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)), ('Linear1.weight', Parameter containing:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], requires_grad=True)), ('Linear1.bias', Parameter containing:
tensor([0., 0.], requires_grad=True))]


AttributeError: module 'quanti' has no attribute 'data_scale_gen'

In [94]:
input_data = torch.randn(5,5)
print(input_data)
input_data *= input_data
print(torch.is_tensor(input_data))


tensor([[ 0.8312, -0.0361,  1.8583,  1.8260,  0.0129],
        [-0.7065,  0.1626,  1.3969, -0.0389, -1.2246],
        [ 1.0453,  0.6418, -0.3205, -0.5269,  0.8623],
        [-1.3874,  1.0944, -1.1311, -0.0636, -1.4719],
        [ 0.9522, -0.7619, -0.7287, -1.6765, -0.2344]])
True
